---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: ghost
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: glob:1.21.*
spec:
  releaseName: ghost
  chart:
    git: ssh://git@github.com/purva1192/flux-get-started
    ref: us-1-east.mertslounge.ca
    path: charts/ghost
  values:
    image: bitnami/ghost:1.21.5-r0
    persistence:
      enabled: false
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
    serviceType: ClusterIP
    mariadb:
      persistence:
        enabled: false
